name: BukkitPlace
version: 1.0
author: NullChips
main: me.nullchips.bukkitplace.BukkitPlace
load: POSTWORLD

commands:
  createplaceworld:
    description: Create the canvas world.
  join:
    description: Join the canvas world.
  sethubspawn:
    description: Set the spawn for the hub.
  hub:
    description: Leave the canvas and go to the hub.

permissions:
  place.ignorecooldown:
    default: false
    description: Ignore the cooldown between placing pixels.
  place.createworld:
    default: op
    description: Create the canvas world.
  place.setspawn:
    default: op
    description: Set the hub for the spawn.