name: BukkitPlace
version: 1.0
author: NullChips
main: me.nullchips.bukkitplace.BukkitPlace
load: POSTWORLD

commands:

permissions:
  place.ignorecooldown:
    default: op
    description: Ignore the cooldown between placing pixels.